[background-image='images/brumjs.png']
[background-size='400px 600px']
== !

*A Software Tool in Many Languages*

Jez Higgins

[NOTE.speaker]
--
Hello everyone - I'm Jez. I'm a freelance software grandad and I'm available to prevent you falling down the old mine shaft, because I have a yawning hole in my diary from the end of this month :)

Dan was kind enough to invite me to speak here at Brum.js just over a year ago, during which I didn't mention JavaScript once. There will be some JavaScript this evening.
--

[background-image='images/software-tools-in-pascal-cover.jpg']
== !

[NOTE.speaker]
--
But first, Pascal!

This is one of my favourite books about software. Written, as you can see, by Brian Kernighan and Bill Plauger, it was first published in 1981 and remains in print.

Are you familiar with Kernighan and Plauger? Both were members of staff at Bell Labs, the home of Unix and consequently of so much of the modern computing landscape. Plauger in the early 70s, Kernighan for a pretty considerable period beyond that.

Kernighan was involved in Unix development, indeed coined the name Unix, and contributed a number of what we now consider "standard Unix" programs particularly around typesetting, and he is the Kof K&R C and also of AWK. He's an amazingly good technical communicator, both as a writer and speaker. There's a Kernighan playlist on the Computerphile Youtube channel, and I absolutely recommend it to you.

I don't think Bill Plauger was directly involved in Unix but he and Kernighan had adjacent offices for a time. When this book was written Plauger had left Bell Labs and founded Whitesmiths, which was the first company to offer a commercial C compiler. Plauger was subsequently involved in both C and {cpp} standardisation, implemented the C and the {cpp} standard libraries, wrote and was editor of C Users Journal for years.

Between them, they've written a number of books, I'd recommend them pretty universally - Plauger's Programming on Purpose in particular, and Kernighan and Pike's The Unix Programming Environment and their Practice of Programming. Wonderful.

Anyway, this book - Software Tools in Pascal.
--

[background-image='images/software-tools-in-pascal-cover.jpg']
== !

[quote]
--
This book teaches how to write good programs that make good tools, by presenting a comprehensive set, each of which provides lessons in design and implementation.
--

[NOTE.speaker]
--
This is the first line of the Preface.

The computing landscape in 1981 was, you won't be surprised to know, rather different to today. The home computer revolution was only just beginning, and those machines were a tiny world of their own. Even in the commercial and academic arena, computing was a very different beast.

When this book was published there were, according to an internal memo, "approximately 800 Unix systems in use outside Bell Labs, with more expected!". The Unix model of computing, of small programs communicating, using text as a common interchange format, wasn't that widely known.

Software Tools in Pascal is both a book about programming, without being a book that teaches you how to program, and a book about the unix philosophy, without being a book that's explicitly about unix.
--

[background-image='images/software-tools-in-pascal-cover.jpg']
== !

[quote]
--
The principles of good programming are presented not as abstract sermons but as concrete lessons in the context of working programs. For example, there is no chapter on "efficiency". Instead, throughout the book there are observations on efficiency as it relates to the particular program being developed. Similarly there is no chapter on "top-down design," nor on "structured programming," nor on "testing and debugging." Instead, all of these disciplines are employed as appropriate in every program shown.
--

[NOTE.speaker]
--
This is also from the Preface.

The modus operandi of the book is, therefore, to present complete programs, and through the discussion of the program development and implementation to illuminate these various aspects of programming as a discipline.

The first chapter, Getting Started, doesn't quite start with Hello World (a program almost certainly first written by Brian Kernighan). It starts with a tiny program to copy the standard input to the standard output, and builds from there, to build progressively more complex programs, including an tar-like file archiver, a grep looky-likey, an ED-style line editor, an typesetter, and a macro processor. All the tools you need, in fact, to write and typeset a book. Weird, huh.
--

[background-image='images/software-tools-in-pascal-cover.jpg']
== !

[NOTE.speaker]
--
When I first read Software Tools in Pascal, I’d just started my first substantial job on a Unix system (in fact four Unix systems, all slightly different) and I was only passingly familiar with a handful of command line tools. The idea that these small programs did simple things, but when combined like some kind of giant tokusatsu robot could do very powerful things was really quite startling.
--

[background-image='images/software-tools-in-pascal-cover.jpg']
== !

[quote]
--
Good Programming is not learned from generalities, but by seeing how significant programs can be made clean, easy to maintain and modify, human-engineered, efficient, and reliable, by the application of common sense and good programming practices. Careful study and imitation of good programs leads to better writing.
--

[NOTE.speaker]
--
After reading and rereading the book several times, last summer I took up the invitation on the cover to imitate, and started reimplementing the programs in the book. I'd just come of a stretch of {cpp} work, {cpp} is a pretty interesting place at the moment, so I chose {cpp}.
--

[background-iframe=https://www.jezuk.co.uk/tags/software-tools-in-c++.html]
== !

[NOTE.speaker]
--
I'm at the start of the third chapter, about 60 pages in. I've got another five chapters, maybe 240 pages, to go. I'll be a while.

But that's ok.
--

[background-image='images/software-tools-software-tools-in-pascal.jpg']
== !

[NOTE.speaker]
--
Because Kernighan and Plauger did the same thing. Software Tools in Pascal is "in Pascal" because it's a rewrite of an earlier book called Software Tools. Software Tools, published in 1976, presented its programs in RatFor - Rational Fortran, which was a language Kernighan invented because Fortran was, well, not rational I guess. RatFor was to Fortran as CoffeeScript is to JavaScript - you run it through a preprocessor and outputs the target language. RatFor could compile to PL/1 too, I think, if you were feeling adventurous.

Pascal had been around since 1970, and by the start of the 80s it was the language of choice for a lot of universities. Certainly, I was taught Pascal in 1987/88, although they recanted the next year and converted us to C for the 88/89 academic year. So, rewriting the book in Pascal was a pragmatic move, in order to get the lessons of the book into more hands.

For this talk, I'm going to take just one of their programs, and present it several times - the original Pascal, in {cpp}, in Lisp (or at least a Lisp), and then in JavaScript.

Why?

Because when Dan asked me to speak, it was the first thing that came into my head and we thought it might be fun :)
--

[background-image='images/stip-contents.png']
[background-size='816px 1178px']
== !

[NOTE.speaker]
--
The book is arranged in 8 chapters, and they kind of build on each other. The first program in the first chapter just copies input to output, and build up through charcounts, linecount, wordcount. The second chapter has programs for stripping or adding tabs, simple text compression, a print-preprocessor (because printing's always been a pain). I'm just getting into file manipulation, the end of that chapter is a program a bit like tar. Chapter 6 builds an ED like line editor, chapter 7 is a nroff-a-like, and chapter 8 is a macro processor. A lot, if not all of these programs, are lightweight versions of the Unix tools we all still use today (which is kind of astonishing in itself).
--

[background-image='images/stip-find.png']
[background-size='825px 1192px']
== !

[NOTE.speaker]
--
For this talk, because I'm an idiot, I decided to do the centre piece of chapter five which is, basically, grep.

This says

find reads its input a line at a time and writes to its output those lines which match the specified text pattern. A text pattern is the concatentation of the following elements +
    c       literal character +
    ?       any character except newline +
    %       beginning of line +
    $       end of line +
    [...]   character class +
    [^...]  negated character class +
    *       closure (zero or more occurrences of previous pattern) +
    @c      escaped characters +
and so on.

(They call the * a closure, where I'd call it a Kleene Star. We're both right! Stephen Kleene invented regular expressions, back in 1951. They didn't really gain any traction until around 1968, partly through the efforts of, that man again, Ken Thompson.)

Anyway ...

This is a proper piece of programming right? This is not trivial - I mean it's not large, but it's not trivial, right?

Before we hit the code, maybe just have a little think about how we might approach this? Any suggestions?
--
